[package]
name = "glimpse"
description = "Cross-platform screen and game capture library for Rust."
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
glimpse_core.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
glimpse_scap_win = { workspace = true, optional = true }
glimpse_obs_hook = { workspace = true, optional = true, features = ["core"] }

[target.'cfg(target_os = "macos")'.dependencies]
glimpse_scap_mac = { workspace = true, optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
glimpse_scap_linux = { workspace = true, optional = true }

[features]
default = ["screen"]
screen = ["glimpse_scap_win", "glimpse_scap_mac", "glimpse_scap_linux"]
game = ["glimpse_obs_hook"]
